#!/bin/bash
#
#   MobileIron Core Apple MDM Certificate expiry date Nagios check script
#
#   Copyright (C) 2016  Gary McConnell - Clever Consulting Srl.
#	www.clevermobile.it
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

# ####################################################
# Set the script name variables
# ####################################################
mSCRIPTNAME=$(basename $0)
mTEMP="$mSCRIPTNAME.XXXXXXXXXX"

# ####################################################
# Check for correct number of arguments/variables set
# ####################################################
if [ -z "$5" ]
  then
    echo "usage: check_mi_mdm <HOSTNAME> <USERNAME> <PASSWORD> <WARNINGDAYS> <CRITICALDAYS>"
    exit 3
fi

# ####################################################
# Set the script Variables
# ####################################################
mVSP=$1
mVSP_USERNAME=$2
mVSP_PASSWORD=$3
mWARNING=$4
mCRITICAL=$5
mCOOKIES=$(mktemp "/tmp/$mTEMP")
mFILETMP1=$(mktemp "/tmp/$mTEMP")
mFILETMP3=$(mktemp "/tmp/$mTEMP")


# ####################################################
# Remote Call to MobileIron Service Login
# ####################################################
curl -k --data "j_username=$mVSP_USERNAME&j_password=$mVSP_PASSWORD&spid=&submit=LOGIN" -H "Referer: https://$mVSP/mifs/login.jsp" https://$mVSP/mifs/j_spring_security_check --cookie-jar $mCOOKIES --location > $mFILETMP1

# get NONCE Value
mCSRFKEY=$(cat $mFILETMP1 | grep csrfKey | tr -s " " | cut -d "\"" -f2)
mCSRFVALUE=$(cat $mFILETMP1 | grep csrfNonce | tr -s " " | cut -d "\"" -f2)



# ####################################################
# get MDM Certificate data
# ####################################################

	mURL="https://$mVSP/mifs/admin/ud.html"
	mOUTFILE=$mFILETMP3
	
	# verifying the version and apply the correct authUserId to the curl command
	mVSP_VERSION=$(cat $mFILETMP1 | grep releaseVersion | tr -s " " | cut -d "." -f1 | cut -d "P" -f2)
	case $mVSP_VERSION in
		 " 6") mVSP_AUTHUSERID=$mVSP_USERNAME;;
		 " 7") mVSP_AUTHUSERID=$(printf $mVSP_USERNAME | base64);;
	esac
		
	curl -k -X POST  \
     	-H Origin:https://$mVSP \
     	-H "$mCSRFKEY: $mCSRFVALUE" \
     	-H "X-Requested-With:XMLHttpRequest" \
     	-H "authUserId:$mVSP_AUTHUSERID" \
     	-H "Content-type:application/x-www-form-urlencoded; charset=UTF-8" \
     	-H "Referer:https://$mVSP/mifs/admin/admin.html" \
     	-d "format=json&cmd=%7B%22id%22:%22getMDMCertificate%22,%22action%22:%22getMDMCertificate%22,%22_index%22:0%7D" \
     	$mURL \
     	--cookie $mCOOKIES \
     	--location > $mOUTFILE
		
        mVALIDITYDATE=$(cat $mFILETMP3 | grep -oP '(?<=validity":")[^"]+' )
        mVALIDITYDATE=${mVALIDITYDATE:0:10}
	mCURRENTDATE=$(date +%s)
	mDAYS_TIMESTAMP=$(($mVALIDITYDATE - $mCURRENTDATE))
	mDAYS=$((mDAYS_TIMESTAMP/86400))
	
	
# ####################################################
# Delete all files created during process
# ####################################################
rm -rf $mCOOKIES
rm -rf $mFILETMP1
rm -rf $mFILETMP3


# ####################################################
# Exit script
# ####################################################
if [[ $mDAYS -gt $mWARNING ]]; then
   echo "MDM OK: $mDAYS Days until expiry"
   exit 0
elif [[ $mDAYS -lt $mCRITICAL ]]; then
   echo " Attention, $mDAYS Days until expiry"
   exit 2
elif [[ $mDAYS -lt $mWARNING ]]; then
   echo " Attention, $mDAYS Days until expiry"
   exit 1
else
   echo "Check failed"
   exit 3
fi
